config/routes.rb
Snami::Application.routes.draw do
  resources :countries

  resources :hottours

  resources :bustours

  resources :replies

end

app/models/bustour.rb
class Bustour < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/hottour.rb
class Hottour < ActiveRecord::Base
end

app/models/reply.rb
class Reply < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bustours_controller.rb
class BustoursController < ApplicationController
  before_action :set_bustour, only: [:show, :edit, :update, :destroy]

  # GET /bustours
  # GET /bustours.json
  def index
    @bustours = Bustour.all
  end

  # GET /bustours/1
  # GET /bustours/1.json
  def show
  end

  # GET /bustours/new
  def new
    @bustour = Bustour.new
  end

  # GET /bustours/1/edit
  def edit
  end

  # POST /bustours
  # POST /bustours.json
  def create
    @bustour = Bustour.new(bustour_params)

    respond_to do |format|
      if @bustour.save
        format.html { redirect_to @bustour, notice: 'Bustour was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bustour }
      else
        format.html { render action: 'new' }
        format.json { render json: @bustour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bustours/1
  # PATCH/PUT /bustours/1.json
  def update
    respond_to do |format|
      if @bustour.update(bustour_params)
        format.html { redirect_to @bustour, notice: 'Bustour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bustour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bustours/1
  # DELETE /bustours/1.json
  def destroy
    @bustour.destroy
    respond_to do |format|
      format.html { redirect_to bustours_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bustour
      @bustour = Bustour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bustour_params
      params.require(:bustour).permit(:name, :price, :imgurl, :about)
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render action: 'show', status: :created, location: @country }
      else
        format.html { render action: 'new' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :imgurl, :about)
    end
end

app/controllers/hottours_controller.rb
class HottoursController < ApplicationController
  before_action :set_hottour, only: [:show, :edit, :update, :destroy]

  # GET /hottours
  # GET /hottours.json
  def index
    @hottours = Hottour.all
  end

  # GET /hottours/1
  # GET /hottours/1.json
  def show
  end

  # GET /hottours/new
  def new
    @hottour = Hottour.new
  end

  # GET /hottours/1/edit
  def edit
  end

  # POST /hottours
  # POST /hottours.json
  def create
    @hottour = Hottour.new(hottour_params)

    respond_to do |format|
      if @hottour.save
        format.html { redirect_to @hottour, notice: 'Hottour was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hottour }
      else
        format.html { render action: 'new' }
        format.json { render json: @hottour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hottours/1
  # PATCH/PUT /hottours/1.json
  def update
    respond_to do |format|
      if @hottour.update(hottour_params)
        format.html { redirect_to @hottour, notice: 'Hottour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hottour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hottours/1
  # DELETE /hottours/1.json
  def destroy
    @hottour.destroy
    respond_to do |format|
      format.html { redirect_to hottours_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hottour
      @hottour = Hottour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hottour_params
      params.require(:hottour).permit(:name, :price, :imgurl, :about)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reply }
      else
        format.html { render action: 'new' }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:username, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bustours_helper.rb
module BustoursHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/hottours_helper.rb
module HottoursHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/bustours/_form.html.erb
<%= form_for(@bustour) do |f| %>
  <% if @bustour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bustour.errors.count, "error") %> prohibited this bustour from being saved:</h2>

      <ul>
      <% @bustour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :imgurl %><br>
    <%= f.text_field :imgurl %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bustours/edit.html.erb
<h1>Editing bustour</h1>

<%= render 'form' %>

<%= link_to 'Show', @bustour %> |
<%= link_to 'Back', bustours_path %>

app/views/bustours/index.html.erb
<h1>Автобусные туры</h1>

<table  border="1px">
  <thead>
    <tr>
      <th>Название</th>
      <th>Цена</th>
      <th>Imgurl</th>
      <th>О туре</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bustours.each do |bustour| %>
      <tr>
        <td><%= bustour.name %></td>
        <td><%= bustour.price %></td>
        <td><img class="photo" src=<%= bustour.imgurl %> width="400" height="200"><td>
        <td><%= bustour.about %></td>
        <td><%= link_to 'Показать', bustour %></td>
        <td><%= link_to 'Редактировать', edit_bustour_path(bustour) %></td>
        <td><%= link_to 'Удалить', bustour, method: :delete, data: { confirm: 'Ты уверена?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый тур', new_bustour_path %>

app/views/bustours/new.html.erb
<h1>Новый автобусный тур</h1>

<%= render 'form' %>

<%= link_to 'Вернуться', bustours_path %>

app/views/bustours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @bustour.name %>
</p>

<p>
  <strong>Цена:</strong>
  <%= @bustour.price %>
</p>

<p>
  <strong>Imgurl:</strong>
  <%= @bustour.imgurl %>
</p>

<p>
  <strong>О туре:</strong>
  <%= @bustour.about %>
</p>

<%= link_to 'Редактировать', edit_bustour_path(@bustour) %> |
<%= link_to 'Вернуться', bustours_path %>

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :imgurl %><br>
    <%= f.text_field :imgurl %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table border="1px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Imgurl</th>
      <th>About</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><img class="photo" src=<%= country.imgurl %> width="400" height="200"><td>
        <td><%= country.about %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Imgurl:</strong>
  <%= @country.imgurl %>
</p>

<p>
  <strong>About:</strong>
  <%= @country.about %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/hottours/_form.html.erb
<%= form_for(@hottour) do |f| %>
  <% if @hottour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hottour.errors.count, "error") %> prohibited this hottour from being saved:</h2>

      <ul>
      <% @hottour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :imgurl %><br>
    <%= f.text_field :imgurl %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hottours/edit.html.erb
<h1>Editing hottour</h1>

<%= render 'form' %>

<%= link_to 'Show', @hottour %> |
<%= link_to 'Back', hottours_path %>

app/views/hottours/index.html.erb
<h1>Горящие туры</h1>

<table  border="1px">
  <thead>
    <tr>
      <th>Название</th>
      <th>Цена</th>
      <th>Imgurl</th>
      <th>О туре</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hottours.each do |hottour| %>
      <tr>
        <td><%= hottour.name %></td>
        <td><%= hottour.price %></td>
        <td><img class="photo" src=<%= hottour.imgurl %> width="400" height="200"><td>
        <td><%= hottour.about %></td>
        <td><%= link_to 'Показать', hottour %></td>
        <td><%= link_to 'Редактировать', edit_hottour_path(hottour) %></td>
        <td><%= link_to 'Удалить', hottour, method: :delete, data: { confirm: 'Ты уверена?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый тур', new_hottour_path %>

app/views/hottours/new.html.erb
<h1>Новый горячий тур</h1>

<%= render 'form' %>

<%= link_to 'Вернуться', hottours_path %>

app/views/hottours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @hottour.name %>
</p>

<p>
  <strong>Цена:</strong>
  <%= @hottour.price %>
</p>

<p>
  <strong>Imgurl:</strong>
  <%= @hottour.imgurl %>
</p>

<p>
  <strong>О туре:</strong>
  <%= @hottour.about %>
</p>

<%= link_to 'Редактировать', edit_hottour_path(@hottour) %> |
<%= link_to 'Вернуться', hottours_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snami</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.username %></td>
        <td><%= reply.text %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @reply.username %>
</p>

<p>
  <strong>Text:</strong>
  <%= @reply.text %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>